export const categories = [
  {
    id: 0,
    name: "Salgados",
  },
  {
    id: 1,
    name: "Doces",
  },
  {
    id: 2,
    name: "Bebidas",
  },
];

export const products = [
  {
    id: 0,
    categoryID: 0,
    name: "Doritos",
    description: "Salgadinho sabor queijo nacho - 55g",
    price: "7.50",
  },
  {
    id: 1,
    categoryID: 0,
    name: "Batata Ruffles Original",
    description: "Salgadinho Elma Chips sabor original - 37g",
    price: "4.39",
  },
  {
    id: 2,
    categoryID: 0,
    name: "Fandangos",
    description: "Salgadinho de Milho - 84g",
    price: "8.86",
  },
  {
    id: 3,
    categoryID: 0,
    name: "Cheetos",
    description: "Salgadinho sabor requeijão - 84g",
    price: "8.86",
  },
  {
    id: 4,
    categoryID: 0,
    name: "Doritos Wassabi",
    description: "Salgadinho sabor wassabi - 78g",
    price: "8.86",
  },
  {
    id: 5,
    categoryID: 0,
    name: "Cebolitos",
    description: "Salgadinho sabor cebola - 84g",
    price: "8.86",
  },
  {
    id: 6,
    categoryID: 0,
    name: "Stiksy",
    description: "Salgadinho Elma Chips - 84g",
    price: "8.86",
  },
  {
    id: 7,
    categoryID: 0,
    name: "Pringles Original",
    description: "Salgadinho de batata - 120g",
    price: "10.00",
  },
  {
    id: 8,
    categoryID: 0,
    name: "Pringles Cebola",
    description: "Salgadinho sabor cebola - 120g",
    price: "10.00",
  },
  {
    id: 9,
    categoryID: 0,
    name: "Pringles Churrasco",
    description: "Salgadinho sabor churrasco - 120g",
    price: "10.00",
  },
  {
    id: 10,
    categoryID: 1,
    name: "Chocolate Milka Avelã",
    description: "Chocolate sabor creme de avelã - 100g",
    price: "19.40",
  },
  {
    id: 11,
    categoryID: 1,
    name: "Chocolate Milka Branco",
    description: "Chocolate branco - 100g",
    price: "17.65",
  },
  {
    id: 12,
    categoryID: 1,
    name: "Kit Kat",
    description: "Chocolate ao leite - 41.5g",
    price: "2.50",
  },
  {
    id: 13,
    categoryID: 1,
    name: "Kit Kat Dark",
    description: "Chocolate amargo - 41.5g",
    price: "2.50",
  },
  {
    id: 14,
    categoryID: 1,
    name: "Kit Kat Branco",
    description: "Chocolate branco - 41.5g",
    price: "2.50",
  },
  {
    id: 15,
    categoryID: 1,
    name: "Bis",
    description: "Chocolate ao leite - 45g",
    price: "2.99",
  },
  {
    id: 16,
    categoryID: 1,
    name: "Bis Oreo",
    description: "Chocolate sabor Oreo - 45g",
    price: "5.99",
  },
  {
    id: 17,
    categoryID: 1,
    name: "Bis Branco",
    description: "Chocolate branco - 45g",
    price: "4.99",
  },
  {
    id: 18,
    categoryID: 1,
    name: "Kit Kat Morango",
    description: "Chocolate sabor morango - 41.5g",
    price: "2.50",
  },
  {
    id: 19,
    categoryID: 1,
    name: "Kit Kat Limão",
    description: "Chocolate sabor limão - 41.5g",
    price: "2.50",
  },
  {
    id: 20,
    categoryID: 2,
    name: "Coca-Cola Original",
    description: "Lata - 350ml",
    price: "4.00",
  },
  {
    id: 21,
    categoryID: 2,
    name: "Coca-Cola Zero",
    description: "Lata - 350ml",
    price: "4.00",
  },
  {
    id: 22,
    categoryID: 2,
    name: "Dr. Pepper Original",
    description: "Lata - 355ml",
    price: "11.00",
  },
  {
    id: 23,
    categoryID: 2,
    name: "H2OH",
    description: "Garrafa - 500ml",
    price: "5.00",
  },
  {
    id: 24,
    categoryID: 2,
    name: "Guaraná",
    description: "Garrafa - 2l",
    price: "5.99",
  },
  {
    id: 25,
    categoryID: 2,
    name: "Pepsi",
    description: "Lata - 2l",
    price: "4.99",
  },
  {
    id: 26,
    categoryID: 2,
    name: "Fanta",
    description: "Garrafa - 2l",
    price: "7.29",
  },
  {
    id: 27,
    categoryID: 2,
    name: "Fanta Uva",
    description: "Lata - 350ml",
    price: "3.99",
  },
  {
    id: 28,
    categoryID: 2,
    name: "Guaraná Zero",
    description: "Lata - 350ml",
    price: "3.71",
  },
  {
    id: 29,
    categoryID: 2,
    name: "Schweppes",
    description: "Lata - 220ml",
    price: "9.90",
  },
];
